name: Java CI with Maven on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 8
            additional-maven-args: "-Pcoveralls"
          - java: 17
            additional-maven-args: >
              sonar:sonar 
              -Dsonar.organization=lbartolini 
              -Dsonar.projectKey=LBartolini_ProgettoAST 
              -Dsonar.host.url=https://sonarcloud.io
  
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: xvfb-run mvn verify ${{ matrix.additional-maven-args }}
      working-directory: com.lbartolini.app.cinema
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit Report
      run: mvn surefire-report:report-only
      working-directory: com.lbartolini.app.cinema
    - name: Archive JUnit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-jdk-${{ matrix.java }}
        path: '**/target/reports'
