name: Java CI with Maven on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 8
            additional-maven-args: "coveralls:report"
          - java: 17
            additional-maven-args: "-DskipCoverage"
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn verify ${{ matrix.additional-maven-args }}
      working-directory: com.lbartolini.app.cinema
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}